### PR TITLE
Upgrade to jQuery UI 1.11.4

### PR DESCRIPTION
**Pull request by rosenfeld**

### CODE REVIEW

**Comment by joliss** [comment]
Perfect, thanks for your PRs - I've merged and released both!

**Comment by rosenfeld** [comment]
Thanks for the new releases :)

**Comment by joliss** [comment]
I've also just added you as a collaborator on this repo, so you can push future updates yourself. If you want me to review something, feel free to still send a pull request, but those updates you sent looked very good - you could just push them directly in the future.

Btw, if you remember, try and also update History.md in addition to VERSIONS.md. I usually just put the commit message as an item in History.md, whenever I commit something.

I've also added you as an owner on Rubygems (I assume rr.rosas@gmail.com is correct, if not please let me know), so you can release stuff. I documented my steps [here](https://github.com/joliss/jquery-ui-rails#releasing).

**Comment by rosenfeld** [comment]
Thank you for trusting me for that, Jo :)

The e-mail is correct and I'll try to remember updating History.md as well. I just saw it's mentioned in the Releasing topic from the README so I guess I'll remember.

If anything is not clear enough to me I'll create a pull request though.

Thanks.

**Pull request closed without merging**
